import { Inter } from "next/font/google";
import "./components/globals.css";
import { ToastContainer } from '@/app/reactToast'
import 'react-toastify/dist/ReactToastify.css';
import { ReduxProvider } from "@/store/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Thats My College - Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          {children}
          <ToastContainer />
        </ReduxProvider>
      </body>
    </html>
  );
}
